[package]
name = "calculaterm"
version = "0.1.0"
description = "A simple and performant calculator that runs in a terminal window!"
authors = ["Chandler King <chandleroking@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
